server:
  port: 9090
spring:
  application:
    name: SmartDiet

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true

  datasource:
    url: jdbc:mysql://localhost/opensourcedb?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

#  data:
#    rest:
#      base-path: /SmartDiet