server:
  port:9090
spring:
  application:
    name: SmartDiet

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true

  datasource:
    url: jdbc:mysql://localhost/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver